import React, { useRef, useState } from 'react';
import Webcam from 'react-webcam';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios"
import Sheet from '@mui/joy/Sheet';
import Button from "@mui/joy/Button"
import Box from '@mui/joy/Box';
import Card from '@mui/joy/Card';
import CardCover from '@mui/joy/CardCover';
import CardContent from '@mui/joy/CardContent';
import CircularProgress from '@mui/joy/CircularProgress';
import Input from '@mui/joy/Input';

import { useEffect } from 'react'
const CameraComponent = () => {
  const webcamRef = useRef(null);

  const capture = () => {
    const imageSrc = webcamRef.current.getScreenshot();
    console.log(imageSrc);
  };

  return (
    <div>
      <Webcam audio={false} ref={webcamRef} />
      {/* <button onClick={capture}>Fotoğraf Çek</button> */}
    </div>
  );
};


export default function Home() {

  const [isTakePhoto, setIsTakePhoto] = useState(false);
  const [input, setInput] = useState("");

  useEffect(() => {
    getApi();
  }, []);
  const getApi = () => {
    axios.get('/api/hello').then((res) => console.log("res", res));
  }
  const handleSave = async () => {
    axios.post('/api/burak',{input})
  }
  const handleChange = () => {
    axios.get('/api/tasi')
  }
  const handleCopy = () => {
    axios.get('/api/kopyala')
  }
  const handleTakePhoto = async () => {
    const response = await handleSave();
    setIsTakePhoto(true);
    axios.post('/api/takePhoto',{input}).then(res=>{
      if(res.status == 200 ){
      setIsTakePhoto(false);
      }
    })

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Sheet sx={{ gap: 2 }}>

          <Box
            sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', p: 0, m: 0 }}
          >
            <Card sx={{ minWidth: 640, minHeight: 460, flexGrow: 1 }}>

              <CardContent sx={{ display: "flex", justifyContent: "center", alignItems: "center" }}>
                {isTakePhoto ? <CircularProgress size="lg" /> :
                  <CameraComponent />
                }
              </CardContent>
            </Card>
          </Box>
          <Box sx={{ display: "flex", justifyContent: "space-around", gap: 2 }} >
            <Button variant="soft" onClick={() => setIsTakePhoto(!isTakePhoto)}>Kamera aç /kapa</Button>
            <Button variant="soft" onClick={handleTakePhoto} >foto çek</Button>
            {/* <button onClick={handleSave} >kaydet</button>
              <button onClick={handleChange} >taşı</button>
              <button onClick={handleCopy} >kopyala</button> */}
          </Box>
          <Box>
            <form
              onSubmit={(event) => {
                event.preventDefault();
              }}
            >
              <Input
                placeholder="dosya adı gir"
                required
                sx={{ mb: 1, fontSize: 'var(--joy-fontSize-sm)' }}
                onChange={(e)=>setInput(e.target.value)}
              />
              {/* <Button type="submit">Submit</Button> */}
            </form>
          </Box>
        </Sheet>
      </main>
    </div>
  )
}
